### ISSUE TITLE
JNLP file should use the complete URL as href

### ISSUE THREAD

**Issue by frosch95** [edvin/fxlauncher#18]
Not using the complete url as href fails, when downloading JNLP file and double click it. More and more browsers are not supporting java and webstart directly.
When double clicking the jnlp file, webstart tries to find the dependencies locally, where no fxlauncher.jar exists, when loaded from webserver.

As you have the url in the settings, you could easily add them to the JNLP file, like 
<jnlp ... href="**http://javafx.ninja/smartcsv/**SmartCSV.fx.jnlp">

**Comment by edvin** [comment]
The JNLP file is created by the `javapackager` command, and generally you don't use it since you would distribute the binary installer instead. If we however could add some more parameters to `javapackage` to make it create a valid JNLP file that would certainly be a bonus.

Information about possible parameters are here:

https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javapackager.html

**Comment by edvin** [comment]
It doesn't seem like `javapackager` supports this, but we could of course modify the JNLP file after it has been created. By the way, this is outside the scope of `fxlauncher`, since it doesn't use `javapackager` or support WebStart (it is an alternative after all), but we could certainly make the Gradle plugin support JNLP file modifications.

**Comment by frosch95** [comment]
I haven't worked with the javapacker, so I have no idea how to fix this. Just realized the effect :-)
Is it better to report this kind of issues at the gradle plugin project? 

Thanks,
Andi

**Comment by edvin** [comment]
Same with this - since FXLauncher was not meant to run under webstart, I'll close this as well :)
