### ISSUE TITLE
Missing cacheDir leads into NPE

### ISSUE THREAD

**Issue by frosch95** [edvin/fxlauncher#19]
Starting the application with webstart without cacheDir information leads into the follwing NPE (you could test it with http://javafx.ninja/smartcsv/SmartCSV.fx.html

java.lang.NullPointerException
	at fxlauncher.Launcher.createApplication(Launcher.java:165)
	at fxlauncher.Launcher.lambda$start$0(Launcher.java:70)

How could I set the parameter? As argument in the jnlp file has not worked out. 

Thanks for your help!
Kindest regards,
Andi

**Comment by edvin** [comment]
This is a bug in fxlauncher, it should check if the parameters map is null, so that the default cacheDir is used. I think it's possible to sett command line parameters as well, but you might just embed them in the app.xml manifest. I also think the gradle plugin needs to support adding parameters to the manifest.

**Comment by edvin** [comment]
I'll be gone most of the day, but I'll get back to you as soon as possible with a solution.

**Comment by frosch95** [comment]
No need to hurry, take your time. The usage of fxlauncher is just a bonus on my project, It is still possible to generate an archieve with a batch file in it. 

Best regards,
Andi

**Comment by edvin** [comment]
Sorry for getting back to you on this so late. I've added a check to avoid the NPE, even though named parameters should be available at this stage, even when loaded via WebStart. However, since FXLauncher is an alternative to WebStart, and was never meant to launch via it, I will not investigate the issue further right now, since the use case is not really there.

FXLauncher works best when you use it in conjunction with javapackager. Is that not an option for you?
