### ISSUE TITLE
Windows Native Installer Link Seems Broken

### ISSUE THREAD

**Issue by matheso** [edvin/fxlauncher#25]
Hi Edvin, 

I noticed that the link to the Window's Native Installer won't work. Are you able to fix this?

[http://fxsamples.tornado.no/CRMApplication-1.0.exe](http://fxsamples.tornado.no/CRMApplication-1.0.exe)

Thank you for your hard work,

Mike

**Comment by edvin** [comment]
Hi, sorry about that, I will fix it once I get to a Windows PC.

But if you're looking for a sample app for FXLauncher, try http://fxldemo.tornado.no instead :)

Or did you want the TornadoFX version specifically? This sample app is a bit out dated, we are working on finalizing the TornadoFX Guide/Book, then we'll start adding more/updated samples to TornadoFX.

**Comment by matheso** [comment]
Appreciate it. To be honest I'm a little confused _what_ I need at the moment. I'm using IntelliJ, with most of my dependencies being connected via external jars, and Maven being responsible for 10 of them (perhaps poor decision). My goal is to be able to update my application once it's distributed to clients, in order to fix bugs, add features, etc. 

Can you recommend which path to take/next step? Thanks for your time.

**Comment by edvin** [comment]
OK, I see. First of all: Forget this sample :) Since you're using Maven, this is the one you should look at:

https://github.com/edvin/fxldemo

I think you would make it easier on yourself if you made sure that Maven handled all of your dependencies. Remember that you can quite easily install those other dependencies in your local maven-repo using the following command:

````bash
mvn install:install-file -Dfile=<filename.jar> -Dversion=<version> -Dpackaging=jar -DartifactId=<artifactId> -DgroupId=<groupId>
```

When Maven handles everything you should be able to use the above sample almost verbatim. If not, don't worry - all you need to do is to copy those dependencies into the `target/app` folder before the `generateManifest` step.

Hope this was helpful, and please ask if you get stuck.

**Comment by matheso** [comment]
It was helpful, indeed. I have some reading to do, thanks again.

**Comment by edvin** [comment]
No problem :) By the way, for Gradle we have a FXLauncher plugin which makes the setup a lot easier, but I use Maven myself with no issues. Just wanted to mention it :)
