### ISSUE TITLE
New Feature: multiple release channels

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxlauncher#42]
Once I had dug into the FxLauncher code a little working on the icon issue I raised, I thought it might be easy to add support for multiple release channels. I really wanted this so I could fully test my app without disturbing my current users. So I dug in and got it working pretty quick.

It uses two setting files - one contains a list of release channels (which would be downloaded from a configured URL) and the other only contains a setting for which channel should be used at launch. The app URLs are different for each channel. The app.xml manifest for each channel specifies a different cacheDir folder, so the downloaded files for the channels are maintained separately. The files are consulted prior to launch to decide which app.xml URL (and thus which cacheDir) to use for launching. Switching channels requires editing the second settings file, but with the addition of a UI component in my app, the user could switch easily between release channels by making a selection in the UI and then restarting.

The implementation currently sits in a layer between the native launcher and FxLauncher. But it would be pretty easy for me to move that into FxLauncher.

Would you be interested in including this feature in FxLauncher?

**Comment by edvin** [comment]
I'd absolutely be interested in the feature. 

Maybe the manifest could contain the list of release channels? We probably don't need another file for that.

How do you plan to autogenerate the different release app.xml files?

**Comment by ChrisLMerrill** [comment]
> Maybe the manifest could contain the list of release channels? We probably don't need another file for that.

Then the list of channels would be duplicated in each app.xml...potentially leading to bugs where the user has somehow acquired different copies with different lists of channels. I'd prefer a single authoritative source for the list of channels. This path keeps 100% compatibility for existing users. If there is no channel file available, there is only one channel and nothing else needs to change.

If I was designing this from scratch, I might not take the same approach.

> How do you plan to autogenerate the different release app.xml files?

Not sure, but my thinking is that the different release channels would be on different branches in the VCS...so each branch would have slightly different paths for deployment URLs, CACHE_DIR, etc in the build config (e.g. build.gradle). Each branch would build exactly one channel, so building and deploying that branch would not affect the other app.xml files. So there would be no change in code required.

**Comment by edvin** [comment]
I don't really see it as a big issue that the channels are duplicated. You might even use it to only allow switching to selected channels when you're one a specific channel. You're not going to have a dozen channels and changing them very often, so this feels like a better trade off than doing another HTTP call to get the channel list. If you want to keep the channels separate, the manifest should at least contain the link to the channels, so that you don't need to try to download the channels file unless there are any.

I think you're probably right about VCS, or even completely separate projects. If you use a build system you might have common code modules and then one main module for each channel, pulling in the common dependencies to produce the complete app.
