### ISSUE TITLE
NPE when using main method

### ISSUE THREAD

**Issue by albertoclarit** [edvin/fxlauncher#81]
I have an NPE
<img width="632" alt="screen shot 2017-07-25 at 12 24 29 pm" src="https://user-images.githubusercontent.com/5086899/28555856-ffd666a2-7134-11e7-8cc2-15722a3139ad.png">

When I use the main method (take note of the redundant null checking on args to make sure)
<img width="479" alt="screen shot 2017-07-25 at 12 25 03 pm" src="https://user-images.githubusercontent.com/5086899/28555885-2550f3e8-7135-11e7-87bd-1046b8a6d174.png">

My Gradle config 
<img width="562" alt="screen shot 2017-07-25 at 12 24 48 pm" src="https://user-images.githubusercontent.com/5086899/28555955-99e8e706-7135-11e7-9234-81ddabd29b17.png">

When Im not using the main method... it works fine.

**Comment by edvin** [comment]
You cannot use a main method with FXLauncher, you must simply point it to your application class that extends `javafx.application.Application` and it will do the rest, including passing any parameters if the app was started with any.

The NPE is not coming from your app class, but from the `Launcher` class of FXLauncher. It is telling of that the `app` instance couldn't be created, most likely because the class you pointed it to is either missing or it's missing a default constructor.

As the error message hints to, there is more information in the log file. I suspect you will find an error starting with "Error creating app class" there.

If this doesn't help you to resolve the issue, please post a minimal example showing the error.

**Comment by albertoclarit** [comment]
I finally understand it ... thanks... this issue is now closed

**Comment by edvin** [comment]
Great! Can you share what the problem was? :)

**Comment by albertoclarit** [comment]
I did not completely understand fxlauncher...

Im using your tornadofx framework and uses the main method in the guide. I thought fxlauncher supports tornadofx directly...

**Comment by edvin** [comment]
That's exactly what it does - it supports JavaFX and TornadoFX directly so it doesn't need a main method :)

**Comment by albertoclarit** [comment]
Oh yes.. I mean the package level main function... 

I was try to initialize a IconFontFX and i thought i could put it in the main method.

But now I was able to do it like this
<img width="468" alt="screen shot 2017-07-25 at 2 43 50 pm" src="https://user-images.githubusercontent.com/5086899/28559115-b9067da8-7147-11e7-860d-420b9538d6b8.png">
